import type { Deal } from './types'

// simulates fetching deals from a database or api.
//
// the 1.2s delay is intentional — makes the suspense streaming behavior
// visible during the demo. in production this would be:
//   - a postgres query (vercel postgres / neon)
//   - a cached api call (with next: { revalidate: 300 })
//   - a redis lookup for hot deal data
//
// the delay also shows that the static shell (hero, nav) arrives
// independently of the dynamic content — that's the whole point of streaming.
export async function getDeals(city: string): Promise<Deal[]> {
  await new Promise((res) => setTimeout(res, 1200))
  return mockDeals.filter((d) => d.city === city)
}

// mock data: 10 deals per city, all 6 categories covered per city.
// varied urgency, realistic copy.

export const mockDeals: Deal[] = [

  // ── HOUSTON ────────────────────────────────────────────────────────────────
  {
    id: 'hou-1',
    title: '50% off brisket platters',
    business: 'Tejas Smokehouse',
    description: 'Flash lunch deal — show student ID at the counter. Dine-in only.',
    city: 'Houston',
    category: 'Food',
    discount: '50% OFF',
    expiresInHours: 1.5,
    emoji: '🍖',
  },
  {
    id: 'hou-2',
    title: 'BOGO breakfast tacos',
    business: 'El Tiempo Cantina',
    description: 'Buy one, get one free until 11am. No coupon needed.',
    city: 'Houston',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 0.75,
    emoji: '🌮',
  },
  {
    id: 'hou-3',
    title: '$5 banh mi — student special',
    business: 'Les Givral\'s Kahve',
    description: 'Any banh mi for $5 with student ID. Lunch hours only.',
    city: 'Houston',
    category: 'Food',
    discount: '$5',
    expiresInHours: 3,
    emoji: '🥖',
  },
  {
    id: 'hou-4',
    title: 'Free drip coffee with any purchase',
    business: 'Common Bond Café',
    description: 'Study fuel. Bring your laptop and student ID.',
    city: 'Houston',
    category: 'Drinks',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '☕',
  },
  {
    id: 'hou-5',
    title: 'Half-price cocktails — 4 to 7pm',
    business: 'Mongoose versus Cobra',
    description: 'All signature cocktails half price during happy hour.',
    city: 'Houston',
    category: 'Drinks',
    discount: '50% OFF',
    expiresInHours: 2,
    emoji: '🍹',
  },
  {
    id: 'hou-6',
    title: 'Student Night — $5 entry',
    business: 'House of Blues Houston',
    description: 'Live local acts. Valid student ID required at door.',
    city: 'Houston',
    category: 'Events',
    discount: '$5 ENTRY',
    expiresInHours: 5,
    emoji: '🎸',
  },
  {
    id: 'hou-7',
    title: 'Free comedy show tonight',
    business: 'Roof Deck at GreenStreet',
    description: 'Open-mic night, no cover. First come first seated.',
    city: 'Houston',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 6,
    emoji: '🎤',
  },
  {
    id: 'hou-8',
    title: '30% off monthly memberships',
    business: 'EaDo Fitness',
    description: 'Student rate, month-to-month. No contract required.',
    city: 'Houston',
    category: 'Fitness',
    discount: '30% OFF',
    expiresInHours: 48,
    emoji: '🏋️',
  },
  {
    id: 'hou-9',
    title: '20% off everything in-store',
    business: 'Cactus Music',
    description: 'Records, merch, accessories. Student ID at checkout.',
    city: 'Houston',
    category: 'Retail',
    discount: '20% OFF',
    expiresInHours: 8,
    emoji: '🎵',
  },
  {
    id: 'hou-10',
    title: '50% off used textbooks',
    business: 'Half Price Books',
    description: 'All used academic titles this week. In-store only.',
    city: 'Houston',
    category: 'Retail',
    discount: '50% OFF',
    expiresInHours: 72,
    emoji: '📚',
  },
  {
    id: 'hou-11',
    title: 'Free quiet study room — 3 hours',
    business: 'Houston Public Library Central',
    description: 'Book a private room with your student ID. Walk-ins welcome today.',
    city: 'Houston',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 9,
    emoji: '📖',
  },
  {
    id: 'hou-12',
    title: '$6 co-working day pass',
    business: 'Greentown Labs Houston',
    description: 'Hot desk + fast WiFi. Students $6 all day. Coffee included.',
    city: 'Houston',
    category: 'Study',
    discount: '$6 PASS',
    expiresInHours: 10,
    emoji: '💻',
  },

  // ── SAN FRANCISCO ──────────────────────────────────────────────────────────
  {
    id: 'sf-1',
    title: 'BOGO burritos',
    business: 'La Taqueria Mission',
    description: 'Buy one, get one free. Cash only. No substitutions.',
    city: 'San Francisco',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 4,
    emoji: '🌯',
  },
  {
    id: 'sf-2',
    title: '$2 off any slice + drink combo',
    business: 'Golden Boy Pizza',
    description: 'North Beach institution. Student discount at the counter.',
    city: 'San Francisco',
    category: 'Food',
    discount: '$2 OFF',
    expiresInHours: 2.5,
    emoji: '🍕',
  },
  {
    id: 'sf-3',
    title: 'Ramen for $9 — student lunch',
    business: 'Mensho Tokyo SF',
    description: 'Full bowl at student rate during lunch hours. ID required.',
    city: 'San Francisco',
    category: 'Food',
    discount: '$9',
    expiresInHours: 1.5,
    emoji: '🍜',
  },
  {
    id: 'sf-4',
    title: 'Happy hour drafts — $4 pints',
    business: 'Zeitgeist Beer Garden',
    description: 'All draft beers $4 from 4–7pm. 21+ with valid ID.',
    city: 'San Francisco',
    category: 'Drinks',
    discount: '$4 PINTS',
    expiresInHours: 2,
    emoji: '🍺',
  },
  {
    id: 'sf-5',
    title: '$3 off any drink — student flash promo',
    business: 'Blue Bottle Coffee',
    description: 'Show a .edu email at the register. Today only.',
    city: 'San Francisco',
    category: 'Drinks',
    discount: '$3 OFF',
    expiresInHours: 6,
    emoji: '☕',
  },
  {
    id: 'sf-6',
    title: 'Tech meetup + free pizza',
    business: 'Galvanize SF',
    description: 'Open to all students. Mention this deal at the door.',
    city: 'San Francisco',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 5,
    emoji: '💻',
  },
  {
    id: 'sf-7',
    title: 'Free gallery opening tonight',
    business: 'Minnesota Street Project',
    description: 'Opening reception, free to all. Wine and snacks provided.',
    city: 'San Francisco',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 7,
    emoji: '🎨',
  },
  {
    id: 'sf-8',
    title: 'First yoga class free',
    business: 'Yoga to the People',
    description: 'Drop-in. Bring a mat, no reservation needed.',
    city: 'San Francisco',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '🧘',
  },
  {
    id: 'sf-9',
    title: 'Free trial boxing class',
    business: 'Gleason\'s Ringside SF',
    description: 'First class free with student ID. Gloves provided.',
    city: 'San Francisco',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 4,
    emoji: '🥊',
  },
  {
    id: 'sf-10',
    title: '15% off sitewide — student rate',
    business: 'Patagonia Union Square',
    description: 'Bring a valid student ID in-store. One use per day.',
    city: 'San Francisco',
    category: 'Retail',
    discount: '15% OFF',
    expiresInHours: 8,
    emoji: '🧥',
  },
  {
    id: 'sf-11',
    title: 'Study pod — 2 hours free',
    business: 'WeWork Mission',
    description: 'Reserve a quiet pod with your .edu email. Today only.',
    city: 'San Francisco',
    category: 'Study',
    discount: '2 HRS FREE',
    expiresInHours: 8,
    emoji: '🖥️',
  },
  {
    id: 'sf-12',
    title: 'Free printing — 50 pages',
    business: 'San Francisco Public Library Main',
    description: 'Free black & white printing for students today. Limit 50 pages.',
    city: 'San Francisco',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 6,
    emoji: '🖨️',
  },

  // ── NEW YORK ───────────────────────────────────────────────────────────────
  {
    id: 'ny-1',
    title: '$1 pizza slices — all afternoon',
    business: "Joe's Pizza",
    description: 'Classic NY slice. No coupon needed, just show up.',
    city: 'New York',
    category: 'Food',
    discount: '$1 SLICE',
    expiresInHours: 1,
    emoji: '🍕',
  },
  {
    id: 'ny-2',
    title: 'BOGO everything bagels',
    business: 'Ess-a-Bagel',
    description: 'Buy one bagel with schmear, get one free until noon.',
    city: 'New York',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 2,
    emoji: '🥯',
  },
  {
    id: 'ny-3',
    title: '$8 soup + bread — student lunch',
    business: 'Hale and Hearty',
    description: 'Any soup with a roll for $8. Student ID at register.',
    city: 'New York',
    category: 'Food',
    discount: '$8',
    expiresInHours: 3,
    emoji: '🥣',
  },
  {
    id: 'ny-4',
    title: '$4 nitro cold brew',
    business: 'Think Coffee',
    description: 'Student price all day. Any size nitro cold brew.',
    city: 'New York',
    category: 'Drinks',
    discount: '$4',
    expiresInHours: 5,
    emoji: '🧋',
  },
  {
    id: 'ny-5',
    title: 'Happy hour wine — $6 a glass',
    business: 'The Wren',
    description: '$6 house wine all evening. 21+ with valid ID.',
    city: 'New York',
    category: 'Drinks',
    discount: '$6 WINE',
    expiresInHours: 2,
    emoji: '🍷',
  },
  {
    id: 'ny-6',
    title: 'Student rush tickets — 50% off',
    business: 'MCC Theater',
    description: 'Same-day rush seats. Student ID required. Limited availability.',
    city: 'New York',
    category: 'Events',
    discount: '50% OFF',
    expiresInHours: 2.5,
    emoji: '🎭',
  },
  {
    id: 'ny-7',
    title: 'Free museum admission 6–9pm',
    business: 'MoMA PS1',
    description: 'Pay-what-you-wish Friday evenings. Student ID gets you in free.',
    city: 'New York',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '🎨',
  },
  {
    id: 'ny-8',
    title: '50% off day pass',
    business: 'YMCA Manhattan',
    description: 'Full facility access at student rate. ID required at front desk.',
    city: 'New York',
    category: 'Fitness',
    discount: '50% OFF',
    expiresInHours: 10,
    emoji: '🏊',
  },
  {
    id: 'ny-9',
    title: 'Free trial run club',
    business: 'New York Road Runners',
    description: 'Join tonight\'s group run free. Meet at Central Park Engineer\'s Gate.',
    city: 'New York',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 6,
    emoji: '🏃',
  },
  {
    id: 'ny-10',
    title: '20% off vintage — student day',
    business: 'Housing Works Thrift',
    description: 'All clothing and accessories 20% off with student ID.',
    city: 'New York',
    category: 'Retail',
    discount: '20% OFF',
    expiresInHours: 9,
    emoji: '👗',
  },
  {
    id: 'ny-11',
    title: 'Strand Books — 15% off all used',
    business: 'The Strand',
    description: '15% off all used books with a student ID. In-store only.',
    city: 'New York',
    category: 'Retail',
    discount: '15% OFF',
    expiresInHours: 11,
    emoji: '📚',
  },
  {
    id: 'ny-12',
    title: 'Free study room — up to 3 hours',
    business: 'NYPL Mid-Manhattan',
    description: 'Book a quiet room with your student ID. Walk-ins welcome.',
    city: 'New York',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 12,
    emoji: '📖',
  },

  // ── PITTSBURGH ─────────────────────────────────────────────────────────────
  {
    id: 'pit-1',
    title: 'Half-price apps — student happy hour',
    business: 'Primanti Brothers',
    description: 'All appetizers 50% off, 3–6pm daily. Show student ID.',
    city: 'Pittsburgh',
    category: 'Food',
    discount: '50% OFF',
    expiresInHours: 2,
    emoji: '🥪',
  },
  {
    id: 'pit-2',
    title: 'Ramen bowl at student price — $8',
    business: 'Nakama Japanese Steakhouse',
    description: 'Full bowl, student ID gets you the $8 rate all day.',
    city: 'Pittsburgh',
    category: 'Food',
    discount: '$8 BOWL',
    expiresInHours: 6,
    emoji: '🍜',
  },
  {
    id: 'pit-3',
    title: '$5 pierogi plate — student lunch',
    business: 'S&D Polish Deli',
    description: 'Pittsburgh classic. Any 4 pierogis + side for $5.',
    city: 'Pittsburgh',
    category: 'Food',
    discount: '$5',
    expiresInHours: 1.5,
    emoji: '🥟',
  },
  {
    id: 'pit-4',
    title: '25% off all specialty drinks',
    business: 'Commonplace Coffee',
    description: 'Student discount all day. Any drink on the menu.',
    city: 'Pittsburgh',
    category: 'Drinks',
    discount: '25% OFF',
    expiresInHours: 5,
    emoji: '☕',
  },
  {
    id: 'pit-5',
    title: '$3 draft beers — student happy hour',
    business: 'The Porch at Schenley',
    description: 'All house drafts $3 from 4–6pm. 21+ ID required.',
    city: 'Pittsburgh',
    category: 'Drinks',
    discount: '$3 DRAFTS',
    expiresInHours: 3,
    emoji: '🍺',
  },
  {
    id: 'pit-6',
    title: 'Penguins student rush — $15 seats',
    business: 'PPG Paints Arena',
    description: 'Limited upper-deck seats. Student ID at box office.',
    city: 'Pittsburgh',
    category: 'Events',
    discount: '$15 SEATS',
    expiresInHours: 3,
    emoji: '🏒',
  },
  {
    id: 'pit-7',
    title: 'Free museum entry — First Friday',
    business: 'Carnegie Museum of Art',
    description: 'Students free every first Friday. No reservation needed.',
    city: 'Pittsburgh',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 4,
    emoji: '🏛️',
  },
  {
    id: 'pit-8',
    title: 'Free fitness class — any format',
    business: 'Pittsburgh Athletic Association',
    description: 'First visit free. Yoga, spin, HIIT — pick any class today.',
    city: 'Pittsburgh',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 5,
    emoji: '🧘',
  },
  {
    id: 'pit-9',
    title: '30% off campus gear',
    business: 'University of Pittsburgh Bookstore',
    description: 'All apparel and accessories 30% off today only.',
    city: 'Pittsburgh',
    category: 'Retail',
    discount: '30% OFF',
    expiresInHours: 7,
    emoji: '🧢',
  },
  {
    id: 'pit-10',
    title: 'Free refills all day',
    business: '61C Café',
    description: 'Classic study spot. Free drip coffee refills. Stay as long as you like.',
    city: 'Pittsburgh',
    category: 'Study',
    discount: 'FREE REFILLS',
    expiresInHours: 7,
    emoji: '🔋',
  },
  {
    id: 'pit-11',
    title: 'Free private study room — 2 hrs',
    business: 'Carnegie Library of Pittsburgh',
    description: 'Walk-in or same-day booking. Quiet, reliable WiFi.',
    city: 'Pittsburgh',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 8,
    emoji: '📖',
  },

  // ── AUSTIN ─────────────────────────────────────────────────────────────────
  {
    id: 'aus-1',
    title: 'Breakfast taco + coffee — $4 combo',
    business: 'Juan in a Million',
    description: 'The classic Don Juan combo at student price. Cash preferred.',
    city: 'Austin',
    category: 'Food',
    discount: '$4 COMBO',
    expiresInHours: 1,
    emoji: '🌮',
  },
  {
    id: 'aus-2',
    title: '$7 BBQ plate — student special',
    business: 'la Barbecue',
    description: 'Brisket + 2 sides for $7. Show student ID at the window.',
    city: 'Austin',
    category: 'Food',
    discount: '$7',
    expiresInHours: 2,
    emoji: '🍖',
  },
  {
    id: 'aus-3',
    title: 'BOGO fish tacos',
    business: 'Torchy\'s Tacos',
    description: 'Buy one, get one on any fish taco. Lunch hours only.',
    city: 'Austin',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 3,
    emoji: '🌮',
  },
  {
    id: 'aus-4',
    title: 'BOGO smoothies',
    business: 'Juiceland',
    description: 'Buy any smoothie, get one equal or lesser value free.',
    city: 'Austin',
    category: 'Drinks',
    discount: 'BOGO',
    expiresInHours: 2,
    emoji: '🥤',
  },
  {
    id: 'aus-5',
    title: '$2 Lone Stars all night',
    business: "Stubb's Amphitheater",
    description: 'Students get $2 domestics. 21+ ID required.',
    city: 'Austin',
    category: 'Drinks',
    discount: '$2 DRINKS',
    expiresInHours: 4,
    emoji: '🍺',
  },
  {
    id: 'aus-6',
    title: 'Live music + free entry before 9pm',
    business: "Emo's Austin",
    description: 'No cover before 9pm with valid student ID.',
    city: 'Austin',
    category: 'Events',
    discount: 'FREE ENTRY',
    expiresInHours: 6,
    emoji: '🎵',
  },
  {
    id: 'aus-7',
    title: 'Free outdoor film screening',
    business: 'Paramount Theatre Austin',
    description: 'Free admission to tonight\'s outdoor film. Gates open at 7pm.',
    city: 'Austin',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 5,
    emoji: '🎬',
  },
  {
    id: 'aus-8',
    title: 'Campus rec guest pass — free',
    business: 'UT Recreational Sports',
    description: 'Bring a friend free on Wednesdays with your UT ID.',
    city: 'Austin',
    category: 'Fitness',
    discount: 'FREE PASS',
    expiresInHours: 8,
    emoji: '🏃',
  },
  {
    id: 'aus-9',
    title: 'Free first bouldering session',
    business: 'Austin Bouldering Project',
    description: 'First visit free with student ID. Shoes and chalk included.',
    city: 'Austin',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 7,
    emoji: '🧗',
  },
  {
    id: 'aus-10',
    title: '25% off all vintage clothing',
    business: 'Waterloo Records & Clothing',
    description: 'Student discount on all vintage apparel today only.',
    city: 'Austin',
    category: 'Retail',
    discount: '25% OFF',
    expiresInHours: 9,
    emoji: '👕',
  },
  {
    id: 'aus-11',
    title: '$5 co-working day pass',
    business: 'Capital Factory',
    description: 'Startup hub co-working. Students $5 all day. Fast Wi-Fi included.',
    city: 'Austin',
    category: 'Study',
    discount: '$5 PASS',
    expiresInHours: 9,
    emoji: '💡',
  },
  {
    id: 'aus-12',
    title: 'Free study lounge + printing',
    business: 'Austin Central Library',
    description: 'Free drop-in study lounge and 20 pages printing with library card.',
    city: 'Austin',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 11,
    emoji: '📖',
  },
]
