import type { Deal } from './types'

/**
 * Simulates fetching deals from a database or API.
 *
 * The 1.2s delay is intentional — it makes the Suspense streaming behavior
 * visible during the demo. In production, this would be:
 *   - A Postgres query (Vercel Postgres / Neon)
 *   - A cached API call (with next: { revalidate: 300 })
 *   - A Redis lookup for hot deal data
 *
 * The delay also demonstrates that the static shell (hero, nav) arrives
 * independently of the dynamic content — exactly the point of streaming.
 */
export async function getDeals(city: string): Promise<Deal[]> {
  await new Promise((res) => setTimeout(res, 1200))
  return mockDeals.filter((d) => d.city === city)
}

// ─── Mock data: 5–6 deals per city ───────────────────────────────────────────
// Designed to showcase: varied categories, urgency gradient, realistic copy.

export const mockDeals: Deal[] = [
  // ── HOUSTON ────────────────────────────────────────────────────────────────
  {
    id: 'hou-1',
    title: '50% off brisket platters',
    business: 'Tejas Smokehouse',
    description: 'Flash lunch deal — show student ID at the counter. Dine-in only.',
    city: 'Houston',
    category: 'Food',
    discount: '50% OFF',
    expiresInHours: 1.5,
    emoji: '🍖',
  },
  {
    id: 'hou-2',
    title: 'BOGO breakfast tacos',
    business: 'El Tiempo Cantina',
    description: 'Buy one, get one free until 11am. No coupon needed.',
    city: 'Houston',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 0.75,
    emoji: '🌮',
  },
  {
    id: 'hou-3',
    title: 'Free drip coffee with any purchase',
    business: 'Common Bond Café',
    description: 'Study fuel. Bring your laptop and student ID.',
    city: 'Houston',
    category: 'Drinks',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '☕',
  },
  {
    id: 'hou-4',
    title: 'Student Night — $5 entry',
    business: 'House of Blues Houston',
    description: 'Live local acts. Valid student ID required at door.',
    city: 'Houston',
    category: 'Events',
    discount: '$5 ENTRY',
    expiresInHours: 5,
    emoji: '🎸',
  },
  {
    id: 'hou-5',
    title: '30% off monthly memberships',
    business: 'EaDo Fitness',
    description: 'Student rate, month-to-month. No contract required.',
    city: 'Houston',
    category: 'Fitness',
    discount: '30% OFF',
    expiresInHours: 48,
    emoji: '🏋️',
  },
  {
    id: 'hou-6',
    title: '50% off used textbooks',
    business: 'Half Price Books',
    description: 'All used academic titles this week. In-store only.',
    city: 'Houston',
    category: 'Retail',
    discount: '50% OFF',
    expiresInHours: 72,
    emoji: '📚',
  },

  // ── SAN FRANCISCO ──────────────────────────────────────────────────────────
  {
    id: 'sf-1',
    title: 'Happy hour drafts — $4 pints',
    business: 'Zeitgeist Beer Garden',
    description: 'All draft beers $4 from 4–7pm. 21+ with valid ID.',
    city: 'San Francisco',
    category: 'Drinks',
    discount: '$4 PINTS',
    expiresInHours: 2,
    emoji: '🍺',
  },
  {
    id: 'sf-2',
    title: 'First yoga class free',
    business: 'Yoga to the People',
    description: 'Drop-in. Bring a mat, no reservation needed.',
    city: 'San Francisco',
    category: 'Fitness',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '🧘',
  },
  {
    id: 'sf-3',
    title: '$3 off any drink — student flash promo',
    business: 'Blue Bottle Coffee',
    description: 'Show a .edu email at the register. Today only.',
    city: 'San Francisco',
    category: 'Drinks',
    discount: '$3 OFF',
    expiresInHours: 6,
    emoji: '☕',
  },
  {
    id: 'sf-4',
    title: 'BOGO burritos',
    business: 'La Taqueria Mission',
    description: 'Buy one, get one free. Cash only. No substitutions.',
    city: 'San Francisco',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 4,
    emoji: '🌯',
  },
  {
    id: 'sf-5',
    title: 'Tech meetup + free pizza',
    business: 'Galvanize SF',
    description: 'Open to all students. Mention this deal at the door.',
    city: 'San Francisco',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 5,
    emoji: '💻',
  },
  {
    id: 'sf-6',
    title: 'Study pod — 2 hours free',
    business: 'WeWork Mission',
    description: 'Reserve a quiet pod with your .edu email. Today only.',
    city: 'San Francisco',
    category: 'Study',
    discount: '2 HRS FREE',
    expiresInHours: 8,
    emoji: '🖥️',
  },

  // ── NEW YORK ───────────────────────────────────────────────────────────────
  {
    id: 'ny-1',
    title: '$1 pizza slices — all afternoon',
    business: "Joe's Pizza",
    description: 'Classic NY slice. No coupon needed, just show up.',
    city: 'New York',
    category: 'Food',
    discount: '$1 SLICE',
    expiresInHours: 1,
    emoji: '🍕',
  },
  {
    id: 'ny-2',
    title: 'BOGO everything bagels',
    business: 'Ess-a-Bagel',
    description: 'Buy one bagel with schmear, get one free until noon.',
    city: 'New York',
    category: 'Food',
    discount: 'BOGO',
    expiresInHours: 2,
    emoji: '🥯',
  },
  {
    id: 'ny-3',
    title: 'Student rush tickets — 50% off',
    business: 'MCC Theater',
    description: 'Same-day rush seats. Student ID required. Limited availability.',
    city: 'New York',
    category: 'Events',
    discount: '50% OFF',
    expiresInHours: 2.5,
    emoji: '🎭',
  },
  {
    id: 'ny-4',
    title: 'Free museum admission 6–9pm',
    business: 'MoMA PS1',
    description: 'Pay-what-you-wish Friday evenings. Student ID gets you in free.',
    city: 'New York',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 3,
    emoji: '🎨',
  },
  {
    id: 'ny-5',
    title: '50% off day pass',
    business: 'YMCA Manhattan',
    description: 'Full facility access at student rate. ID required at front desk.',
    city: 'New York',
    category: 'Fitness',
    discount: '50% OFF',
    expiresInHours: 10,
    emoji: '🏊',
  },
  {
    id: 'ny-6',
    title: 'Free study room — up to 3 hours',
    business: 'NYPL Mid-Manhattan',
    description: 'Book a quiet room with your student ID. Walk-ins welcome.',
    city: 'New York',
    category: 'Study',
    discount: 'FREE',
    expiresInHours: 12,
    emoji: '📖',
  },

  // ── PITTSBURGH ─────────────────────────────────────────────────────────────
  {
    id: 'pit-1',
    title: 'Half-price apps — student happy hour',
    business: 'Primanti Brothers',
    description: 'All appetizers 50% off, 3–6pm daily. Show student ID.',
    city: 'Pittsburgh',
    category: 'Food',
    discount: '50% OFF',
    expiresInHours: 2,
    emoji: '🥪',
  },
  {
    id: 'pit-2',
    title: 'Ramen bowl at student price — $8',
    business: 'Nakama Japanese Steakhouse',
    description: 'Full bowl, student ID gets you the $8 rate all day.',
    city: 'Pittsburgh',
    category: 'Food',
    discount: '$8 BOWL',
    expiresInHours: 6,
    emoji: '🍜',
  },
  {
    id: 'pit-3',
    title: 'Penguins student rush — $15 seats',
    business: 'PPG Paints Arena',
    description: 'Limited upper-deck seats. Student ID at box office.',
    city: 'Pittsburgh',
    category: 'Events',
    discount: '$15 SEATS',
    expiresInHours: 3,
    emoji: '🏒',
  },
  {
    id: 'pit-4',
    title: 'Free museum entry — First Friday',
    business: 'Carnegie Museum of Art',
    description: 'Students free every first Friday. No reservation needed.',
    city: 'Pittsburgh',
    category: 'Events',
    discount: 'FREE',
    expiresInHours: 4,
    emoji: '🏛️',
  },
  {
    id: 'pit-5',
    title: '25% off all specialty drinks',
    business: 'Commonplace Coffee',
    description: 'Student discount all day. Any drink on the menu.',
    city: 'Pittsburgh',
    category: 'Drinks',
    discount: '25% OFF',
    expiresInHours: 5,
    emoji: '☕',
  },
  {
    id: 'pit-6',
    title: 'Free refills all day',
    business: '61C Café',
    description: 'Classic study spot. Free drip coffee refills. Stay as long as you like.',
    city: 'Pittsburgh',
    category: 'Study',
    discount: 'FREE REFILLS',
    expiresInHours: 7,
    emoji: '🔋',
  },

  // ── AUSTIN ─────────────────────────────────────────────────────────────────
  {
    id: 'aus-1',
    title: 'Breakfast taco + coffee — $4 combo',
    business: 'Juan in a Million',
    description: 'The classic Don Juan combo at student price. Cash preferred.',
    city: 'Austin',
    category: 'Food',
    discount: '$4 COMBO',
    expiresInHours: 1,
    emoji: '🌮',
  },
  {
    id: 'aus-2',
    title: 'BOGO smoothies',
    business: 'Juiceland',
    description: 'Buy any smoothie, get one equal or lesser value free.',
    city: 'Austin',
    category: 'Drinks',
    discount: 'BOGO',
    expiresInHours: 2,
    emoji: '🥤',
  },
  {
    id: 'aus-3',
    title: 'Live music + $2 Lone Stars all night',
    business: "Stubb's Amphitheater",
    description: 'Local act tonight. Students get $2 domestics. 21+ ID required.',
    city: 'Austin',
    category: 'Events',
    discount: '$2 DRINKS',
    expiresInHours: 4,
    emoji: '🎶',
  },
  {
    id: 'aus-4',
    title: 'Free entry — student night',
    business: "Emo's Austin",
    description: 'No cover before 10pm with valid student ID.',
    city: 'Austin',
    category: 'Events',
    discount: 'FREE ENTRY',
    expiresInHours: 6,
    emoji: '🎵',
  },
  {
    id: 'aus-5',
    title: 'Campus rec guest pass — free',
    business: 'UT Recreational Sports',
    description: 'Bring a friend free on Wednesdays with your UT ID.',
    city: 'Austin',
    category: 'Fitness',
    discount: 'FREE PASS',
    expiresInHours: 8,
    emoji: '🏃',
  },
  {
    id: 'aus-6',
    title: '$5 co-working day pass',
    business: 'Capital Factory',
    description: 'Startup hub co-working. Students $5 all day. Fast Wi-Fi included.',
    city: 'Austin',
    category: 'Study',
    discount: '$5 PASS',
    expiresInHours: 9,
    emoji: '💡',
  },
]
